// ui/src/components/MediaControls.tsx
import React from 'react';
import { observer } from 'mobx-react-lite';
import webrtcStore from "@/stores/webrtc.store";
import roomStore from "@/stores/room.store";

// ============================================================================
// UTILITY FUNCTIONS
// ============================================================================

const getConnectionStatusColor = (connectionState: RTCPeerConnectionState): string => {
    switch (connectionState) {
        case 'connected': return 'bg-green-500';
        case 'connecting': return 'bg-yellow-500';
        case 'new': return 'bg-blue-500';
        case 'disconnected':
        case 'failed': return 'bg-red-500';
        default: return 'bg-gray-500';
    }
};

const getConnectionStatusText = (connectionState: RTCPeerConnectionState): string => {
    switch (connectionState) {
        case 'connected': return 'Connected';
        case 'connecting': return 'Connecting...';
        case 'new': return 'Establishing...';
        case 'disconnected': return 'Disconnected';
        case 'failed': return 'Failed';
        default: return 'Unknown';
    }
};

// ============================================================================
// MAIN COMPONENT
// ============================================================================

const MediaControls: React.FC = observer(() => {
    const handleStartMedia = async () => {
        try {
            await webrtcStore.startMedia({ video: true, audio: true });

            // Auto-connect to all existing participants
            if (roomStore.otherParticipants.length > 0) {
                await webrtcStore.connectToAllParticipants();
            }
        } catch (error) {
            console.error('Failed to start media:', error);
        }
    };

    const handleStartScreenShare = async () => {
        try {
            await webrtcStore.startScreenShare();
        } catch (error) {
            console.error('Failed to start screen share:', error);
        }
    };

    const handleStopMedia = () => {
        webrtcStore.stopMedia();
    };

    const handleToggleVideo = () => {
        webrtcStore.toggleVideo();
    };

    const handleToggleAudio = () => {
        webrtcStore.toggleAudio();
    };

    const totalOtherParticipants = roomStore.otherParticipants.length;
    const connectedPeers = webrtcStore.connectedPeersCount;
    const totalConnections = webrtcStore.peerConnections.size;
    const isConnecting = webrtcStore.isConnecting;
    const hasFailedConnections = webrtcStore.hasFailedConnections;

    return (
        <div className="space-y-4">
            <h3 className="text-lg font-semibold text-gray-800">Media Controls</h3>

            {/* Media Control Buttons */}
            <div className="space-y-3">
                {!webrtcStore.isMediaActive && (
                    <>
                        {/* Start Camera */}
                        <button
                            onClick={handleStartMedia}
                            disabled={!webrtcStore.canStartMedia}
                            className="w-full flex items-center justify-center gap-2 px-4 py-3 bg-green-500 text-white rounded-lg hover:bg-green-600 disabled:bg-gray-400 disabled:cursor-not-allowed transition-colors"
                        >
                            <svg className="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
                                <path fillRule="evenodd" d="M4 3a2 2 0 00-2 2v10a2 2 0 002 2h12a2 2 0 002-2V5a2 2 0 00-2-2H4zm12 12H4l4-8 3 6 2-4 3 6z" clipRule="evenodd" />
                            </svg>
                            Start Camera
                        </button>

                        {/* Start Screen Share */}
                        <button
                            onClick={handleStartScreenShare}
                            disabled={!webrtcStore.canStartMedia}
                            className="w-full flex items-center justify-center gap-2 px-4 py-3 bg-blue-500 text-white rounded-lg hover:bg-blue-600 disabled:bg-gray-400 disabled:cursor-not-allowed transition-colors"
                        >
                            <svg className="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
                                <path fillRule="evenodd" d="M3 4a1 1 0 011-1h12a1 1 0 011 1v8a1 1 0 01-1 1H4a1 1 0 01-1-1V4zm2 1v6h10V5H5z" clipRule="evenodd" />
                                <path d="M8 15v1h4v-1H8z" />
                                <path d="M6 16h8v1H6v-1z" />
                            </svg>
                            Start Screen Share
                        </button>
                    </>
                )}

                {webrtcStore.isMediaActive && (
                    <>
                        {/* Media Toggle Controls */}
                        <div className="grid grid-cols-2 gap-3">
                            {/* Toggle Video */}
                            <button
                                onClick={handleToggleVideo}
                                className={`flex items-center justify-center gap-2 px-4 py-2 rounded-lg transition-colors ${
                                    webrtcStore.hasVideo
                                        ? 'bg-gray-500 text-white hover:bg-gray-600'
                                        : 'bg-red-500 text-white hover:bg-red-600'
                                }`}
                            >
                                <svg className="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
                                    {webrtcStore.hasVideo ? (
                                        <path fillRule="evenodd" d="M4 3a2 2 0 00-2 2v10a2 2 0 002 2h12a2 2 0 002-2V5a2 2 0 00-2-2H4zm12 12H4l4-8 3 6 2-4 3 6z" clipRule="evenodd" />
                                    ) : (
                                        <path fillRule="evenodd" d="M3.707 2.293a1 1 0 00-1.414 1.414l14 14a1 1 0 001.414-1.414l-1.473-1.473A2 2 0 0017 14V6a2 2 0 00-2-2H5.414l-1.707-1.707zM5.414 6L15 15.586V14a1 1 0 112 0v4a1 1 0 01-1 1H4a1 1 0 01-1-1V6h2.414z" clipRule="evenodd" />
                                    )}
                                </svg>
                                {webrtcStore.hasVideo ? 'Camera On' : 'Camera Off'}
                            </button>

                            {/* Toggle Audio */}
                            <button
                                onClick={handleToggleAudio}
                                className={`flex items-center justify-center gap-2 px-4 py-2 rounded-lg transition-colors ${
                                    webrtcStore.hasAudio
                                        ? 'bg-gray-500 text-white hover:bg-gray-600'
                                        : 'bg-red-500 text-white hover:bg-red-600'
                                }`}
                            >
                                <svg className="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
                                    {webrtcStore.hasAudio ? (
                                        <path fillRule="evenodd" d="M9.383 3.076A1 1 0 0110 4v12a1 1 0 01-1.707.707L4.586 13H2a1 1 0 01-1-1V8a1 1 0 011-1h2.586l3.707-3.707a1 1 0 011.09-.217zM12.293 7.293a1 1 0 011.414 0L15 8.586l1.293-1.293a1 1 0 111.414 1.414L16.414 10l1.293 1.293a1 1 0 01-1.414 1.414L15 11.414l-1.293 1.293a1 1 0 01-1.414-1.414L13.586 10l-1.293-1.293a1 1 0 010-1.414z" clipRule="evenodd" />
                                    ) : (
                                        <path fillRule="evenodd" d="M9.383 3.076A1 1 0 0110 4v12a1 1 0 01-1.707.707L4.586 13H2a1 1 0 01-1-1V8a1 1 0 011-1h2.586l3.707-3.707a1 1 0 011.09-.217zM15.657 6.343a1 1 0 011.414 0L19 8.272l1.929-1.929a1 1 0 111.414 1.414L20.414 9.686l1.929 1.929a1 1 0 01-1.414 1.414L19 11.1l-1.929 1.929a1 1 0 01-1.414-1.414l1.929-1.929-1.929-1.929a1 1 0 010-1.414z" clipRule="evenodd" />
                                    )}
                                </svg>
                                {webrtcStore.hasAudio ? 'Mic On' : 'Mic Off'}
                            </button>
                        </div>

                        {/* Switch Media Source */}
                        <div className="grid grid-cols-2 gap-3">
                            {!webrtcStore.isScreenSharing && (
                                <button
                                    onClick={handleStartScreenShare}
                                    className="flex items-center justify-center gap-2 px-4 py-2 bg-blue-500 text-white rounded-lg hover:bg-blue-600 transition-colors"
                                >
                                    <svg className="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
                                        <path fillRule="evenodd" d="M3 4a1 1 0 011-1h12a1 1 0 011 1v8a1 1 0 01-1 1H4a1 1 0 01-1-1V4zm2 1v6h10V5H5z" clipRule="evenodd" />
                                    </svg>
                                    Share Screen
                                </button>
                            )}

                            {/* Stop Media */}
                            <button
                                onClick={handleStopMedia}
                                className="flex items-center justify-center gap-2 px-4 py-2 bg-red-500 text-white rounded-lg hover:bg-red-600 transition-colors"
                            >
                                <svg className="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
                                    <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8 7a1 1 0 00-1 1v4a1 1 0 001 1h4a1 1 0 001-1V8a1 1 0 00-1-1H8z" clipRule="evenodd" />
                                </svg>
                                Stop Media
                            </button>
                        </div>
                    </>
                )}
            </div>

            {/* Enhanced Connection Status */}
            {webrtcStore.isMediaActive && totalOtherParticipants > 0 && (
                <div className="p-4 bg-gray-50 rounded-lg">
                    <div className="flex items-center justify-between mb-3">
                        <h4 className="text-sm font-medium text-gray-800">Connection Status</h4>
                        <div className="flex items-center gap-2">
                            {isConnecting && (
                                <div className="w-2 h-2 bg-yellow-500 rounded-full animate-pulse"></div>
                            )}
                            {hasFailedConnections && (
                                <div className="w-2 h-2 bg-red-500 rounded-full"></div>
                            )}
                            <span className="text-sm font-medium text-gray-800">
                                {connectedPeers} / {totalOtherParticipants} connected
                            </span>
                        </div>
                    </div>

                    {/* Overall Status Bar */}
                    <div className="mb-3">
                        <div className="flex justify-between text-xs text-gray-600 mb-1">
                            <span>Connection Progress</span>
                            <span>{Math.round((connectedPeers / totalOtherParticipants) * 100)}%</span>
                        </div>
                        <div className="w-full bg-gray-200 rounded-full h-2">
                            <div
                                className={`h-2 rounded-full transition-all duration-300 ${
                                    connectedPeers === totalOtherParticipants ? 'bg-green-500' :
                                        connectedPeers > 0 ? 'bg-yellow-500' : 'bg-red-500'
                                }`}
                                style={{ width: `${(connectedPeers / totalOtherParticipants) * 100}%` }}
                            ></div>
                        </div>
                    </div>

                    {/* Individual Connection Status */}
                    <div className="space-y-2">
                        {Array.from(webrtcStore.peerConnections.values()).map((peer) => {
                            const statusColor = getConnectionStatusColor(peer.connectionState);
                            const statusText = getConnectionStatusText(peer.connectionState);
                            const isConnecting = ['connecting', 'new'].includes(peer.connectionState);

                            return (
                                <div key={peer.participantId} className="flex items-center justify-between text-xs bg-white p-2 rounded">
                                    <div className="flex items-center gap-2">
                                        <div className={`w-2 h-2 rounded-full ${statusColor} ${
                                            isConnecting ? 'animate-pulse' : ''
                                        }`}></div>
                                        <span className="text-gray-800 truncate max-w-[120px] font-medium">
                                            {peer.userName}
                                        </span>
                                    </div>
                                    <div className="flex items-center gap-2">
                                        {/* Connection Quality Indicator */}
                                        {peer.connectionState === 'connected' && (
                                            <div className="flex gap-1">
                                                <div className="w-1 h-3 bg-green-400 rounded-full"></div>
                                                <div className="w-1 h-3 bg-green-400 rounded-full"></div>
                                                <div className="w-1 h-3 bg-green-400 rounded-full"></div>
                                            </div>
                                        )}
                                        <span className={`font-medium ${
                                            peer.connectionState === 'connected' ? 'text-green-600' :
                                                isConnecting ? 'text-yellow-600' :
                                                    'text-red-600'
                                        }`}>
                                            {statusText}
                                        </span>
                                    </div>
                                </div>
                            );
                        })}

                        {/* Show participants without connections */}
                        {roomStore.otherParticipants
                            .filter(p => !webrtcStore.peerConnections.has(p.socketId))
                            .map((participant) => (
                                <div key={participant.socketId} className="flex items-center justify-between text-xs bg-white p-2 rounded">
                                    <div className="flex items-center gap-2">
                                        <div className="w-2 h-2 rounded-full bg-orange-500 animate-pulse"></div>
                                        <span className="text-gray-800 truncate max-w-[120px] font-medium">
                                            {participant.userName}
                                        </span>
                                    </div>
                                    <span className="font-medium text-orange-600">
                                        Waiting...
                                    </span>
                                </div>
                            ))
                        }
                    </div>

                    {/* Advanced Status Information */}
                    {totalConnections > 0 && (
                        <div className="mt-3 pt-3 border-t border-gray-200">
                            <div className="grid grid-cols-2 gap-4 text-xs">
                                <div>
                                    <span className="text-gray-600">Total Connections:</span>
                                    <span className="ml-1 font-medium text-gray-800">{totalConnections}</span>
                                </div>
                                <div>
                                    <span className="text-gray-600">Connected:</span>
                                    <span className="ml-1 font-medium text-green-600">{connectedPeers}</span>
                                </div>
                            </div>

                            {/* ICE Candidates Status */}
                            {webrtcStore.pendingCandidatesCount > 0 && (
                                <div className="mt-2 flex items-center gap-1 text-xs text-blue-600">
                                    <svg className="w-3 h-3 animate-spin" fill="currentColor" viewBox="0 0 20 20">
                                        <path fillRule="evenodd" d="M4 2a1 1 0 011 1v2.101a7.002 7.002 0 0111.601 2.566 1 1 0 11-1.885.666A5.002 5.002 0 005.999 7H8a1 1 0 010 2H4a1 1 0 01-1-1V3a1 1 0 011-1zm.008 9.057a1 1 0 011.276.61A5.002 5.002 0 0014.001 13H12a1 1 0 110-2h4a1 1 0 011 1v4a1 1 0 11-2 0v-2.101a7.002 7.002 0 01-11.601-2.566 1 1 0 01.61-1.276z" clipRule="evenodd" />
                                    </svg>
                                    <span>Buffering {webrtcStore.pendingCandidatesCount} ICE candidate(s)</span>
                                </div>
                            )}

                            {/* Retry Status */}
                            {webrtcStore.activeRetryCount > 0 && (
                                <div className="mt-2 flex items-center gap-1 text-xs text-yellow-600">
                                    <svg className="w-3 h-3 animate-spin" fill="currentColor" viewBox="0 0 20 20">
                                        <path fillRule="evenodd" d="M4 2a1 1 0 011 1v2.101a7.002 7.002 0 0111.601 2.566 1 1 0 11-1.885.666A5.002 5.002 0 005.999 7H8a1 1 0 010 2H4a1 1 0 01-1-1V3a1 1 0 011-1zm.008 9.057a1 1 0 011.276.61A5.002 5.002 0 0014.001 13H12a1 1 0 110-2h4a1 1 0 011 1v4a1 1 0 11-2 0v-2.101a7.002 7.002 0 01-11.601-2.566 1 1 0 01.61-1.276z" clipRule="evenodd" />
                                    </svg>
                                    <span>Retrying {webrtcStore.activeRetryCount} connection(s)</span>
                                </div>
                            )}
                        </div>
                    )}
                </div>
            )}

            {/* Media Status Information */}
            {webrtcStore.isMediaActive && (
                <div className="p-4 bg-blue-50 border border-blue-200 rounded-lg">
                    <h4 className="text-sm font-medium text-blue-800 mb-3">Local Media Status</h4>

                    <div className="space-y-2">
                        {/* Media Type */}
                        <div className="flex items-center justify-between text-sm">
                            <span className="text-blue-700">Source:</span>
                            <div className="flex items-center gap-1">
                                {webrtcStore.isScreenSharing ? (
                                    <>
                                        <svg className="w-4 h-4 text-blue-600" fill="currentColor" viewBox="0 0 20 20">
                                            <path fillRule="evenodd" d="M3 4a1 1 0 011-1h12a1 1 0 011 1v8a1 1 0 01-1 1H4a1 1 0 01-1-1V4zm2 1v6h10V5H5z" clipRule="evenodd" />
                                        </svg>
                                        <span className="font-medium text-blue-800">Screen Share</span>
                                    </>
                                ) : (
                                    <>
                                        <svg className="w-4 h-4 text-blue-600" fill="currentColor" viewBox="0 0 20 20">
                                            <path fillRule="evenodd" d="M4 3a2 2 0 00-2 2v10a2 2 0 002 2h12a2 2 0 002-2V5a2 2 0 00-2-2H4zm12 12H4l4-8 3 6 2-4 3 6z" clipRule="evenodd" />
                                        </svg>
                                        <span className="font-medium text-blue-800">Camera</span>
                                    </>
                                )}
                            </div>
                        </div>

                        {/* Video Status */}
                        <div className="flex items-center justify-between text-sm">
                            <span className="text-blue-700">Video:</span>
                            <div className="flex items-center gap-1">
                                <div className={`w-2 h-2 rounded-full ${webrtcStore.hasVideo ? 'bg-green-500' : 'bg-red-500'}`}></div>
                                <span className={`font-medium ${webrtcStore.hasVideo ? 'text-green-600' : 'text-red-600'}`}>
                                    {webrtcStore.hasVideo ? 'On' : 'Off'}
                                </span>
                            </div>
                        </div>

                        {/* Audio Status */}
                        <div className="flex items-center justify-between text-sm">
                            <span className="text-blue-700">Audio:</span>
                            <div className="flex items-center gap-1">
                                <div className={`w-2 h-2 rounded-full ${webrtcStore.hasAudio ? 'bg-green-500' : 'bg-red-500'}`}></div>
                                <span className={`font-medium ${webrtcStore.hasAudio ? 'text-green-600' : 'text-red-600'}`}>
                                    {webrtcStore.hasAudio ? 'On' : 'Off'}
                                </span>
                            </div>
                        </div>

                        {/* Stream Details */}
                        {webrtcStore.localStream && (
                            <div className="pt-2 border-t border-blue-200">
                                <div className="text-xs space-y-1">
                                    <div className="flex justify-between">
                                        <span className="text-blue-600">Video Tracks:</span>
                                        <span className="font-mono text-blue-800">
                                            {webrtcStore.localStream.getVideoTracks().length}
                                        </span>
                                    </div>
                                    <div className="flex justify-between">
                                        <span className="text-blue-600">Audio Tracks:</span>
                                        <span className="font-mono text-blue-800">
                                            {webrtcStore.localStream.getAudioTracks().length}
                                        </span>
                                    </div>
                                    <div className="flex justify-between">
                                        <span className="text-blue-600">Stream ID:</span>
                                        <span className="font-mono text-blue-800 text-xs truncate max-w-[100px]">
                                            {webrtcStore.localStream.id}
                                        </span>
                                    </div>
                                </div>
                            </div>
                        )}
                    </div>
                </div>
            )}

            {/* Error Display */}
            {webrtcStore.mediaError && (
                <div className="p-3 bg-red-50 border border-red-200 rounded-lg">
                    <div className="flex items-center gap-2 text-sm text-red-700">
                        <svg className="w-4 h-4" fill="currentColor" viewBox="0 0 20 20">
                            <path fillRule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7 4a1 1 0 11-2 0 1 1 0 012 0zm-1-9a1 1 0 00-1 1v4a1 1 0 102 0V6a1 1 0 00-1-1z" clipRule="evenodd" />
                        </svg>
                        <span className="font-medium">Media Error:</span>
                    </div>
                    <p className="text-sm text-red-600 mt-1">{webrtcStore.mediaError}</p>
                </div>
            )}

            {/* Help Information */}
            <div className="p-3 bg-gray-50 border border-gray-200 rounded-lg">
                <h4 className="text-sm font-medium text-gray-800 mb-2">Controls Guide</h4>
                <div className="text-xs text-gray-600 space-y-1">
                    <div><strong>Camera:</strong> Share video and audio with participants</div>
                    <div><strong>Screen Share:</strong> Share your screen instead of camera</div>
                    <div><strong>Toggles:</strong> Mute/unmute during active calls</div>
                    {totalOtherParticipants > 0 && (
                        <div className="pt-1 border-t border-gray-300">
                            <strong>Tip:</strong> Connections establish automatically when you start media
                        </div>
                    )}
                </div>
            </div>

            {/* Quick Actions */}
            {webrtcStore.isMediaActive && totalOtherParticipants > 0 && (
                <div className="flex gap-2">
                    <button
                        onClick={() => webrtcStore.connectToAllParticipants()}
                        className="flex-1 text-xs px-3 py-2 bg-blue-100 text-blue-700 rounded hover:bg-blue-200 transition-colors"
                    >
                        Reconnect All
                    </button>
                    <button
                        onClick={() => webrtcStore.clearLogs()}
                        className="flex-1 text-xs px-3 py-2 bg-gray-100 text-gray-700 rounded hover:bg-gray-200 transition-colors"
                    >
                        Clear Logs
                    </button>
                </div>
            )}
        </div>
    );
});

export default MediaControls;

// ui-nuxt/components/video/MediaControls.vue
<script setup lang="ts">
import { useWebRTCStore } from '~/stores/webrtc.store'
import { useRoomStore } from '~/stores/room.store'
import { ref, computed, onMounted } from 'vue'

// Stores
const webrtcStore = useWebRTCStore()
const roomStore = useRoomStore()

// Local state
const showDeviceSettings = ref(false)
const selectedQuality = ref('720p')

// Computed
const connectedCount = computed(() => {
  return Array.from(webrtcStore.peerConnections.values())
      .filter(peer => peer.connection.connectionState === 'connected').length
})

const otherParticipantsCount = computed(() => {
  return roomStore.participants.filter(
      p => p.socketId !== roomStore.currentParticipant?.socketId
  ).length
})

const connectionProgress = computed(() => {
  if (otherParticipantsCount.value === 0) return 100
  return (connectedCount.value / otherParticipantsCount.value) * 100
})

const peerConnectionsArray = computed(() => {
  return Array.from(webrtcStore.peerConnections.values())
})

const videoDeviceItems = computed(() => {
  return webrtcStore.availableDevices.videoDevices.map(device => ({
    title: device.label || `Camera ${device.deviceId.slice(0, 8)}`,
    value: device.deviceId
  }))
})

const audioDeviceItems = computed(() => {
  return webrtcStore.availableDevices.audioDevices.map(device => ({
    title: device.label || `Microphone ${device.deviceId.slice(0, 8)}`,
    value: device.deviceId
  }))
})

const qualityOptions = [
  { title: 'High (1080p)', value: '1080p' },
  { title: 'Medium (720p)', value: '720p' },
  { title: 'Low (480p)', value: '480p' }
]

// Methods
const startMedia = async () => {
  try {
    await webrtcStore.startMedia()
  } catch (error) {
    console.error('Failed to start media:', error)
  }
}

const stopMedia = () => {
  webrtcStore.stopMedia()
}

const toggleVideo = () => {
  webrtcStore.toggleVideo()
}

const toggleAudio = () => {
  webrtcStore.toggleAudio()
}

const toggleScreenShare = async () => {
  try {
    if (webrtcStore.isScreenSharing) {
      await webrtcStore.stopScreenShare()
    } else {
      await webrtcStore.startScreenShare()
    }
  } catch (error) {
    console.error('Failed to toggle screen share:', error)
  }
}

const refreshDevices = async () => {
  try {
    await webrtcStore.getAvailableDevices()
  } catch (error) {
    console.error('Failed to refresh devices:', error)
  }
}

const onVideoDeviceChange = async (deviceId: string) => {
  try {
    await webrtcStore.switchVideoDevice(deviceId)
  } catch (error) {
    console.error('Failed to switch video device:', error)
  }
}

const onAudioDeviceChange = async (deviceId: string) => {
  try {
    await webrtcStore.switchAudioDevice(deviceId)
  } catch (error) {
    console.error('Failed to switch audio device:', error)
  }
}

// Helper functions
const getConnectionColor = (state: RTCPeerConnectionState) => {
  switch (state) {
    case 'connected': return 'success'
    case 'connecting': return 'warning'
    case 'new': return 'info'
    case 'disconnected':
    case 'failed': return 'error'
    default: return 'grey'
  }
}

const getConnectionIcon = (state: RTCPeerConnectionState) => {
  switch (state) {
    case 'connected': return 'mdi-check'
    case 'connecting': return 'mdi-loading'
    case 'new': return 'mdi-circle-outline'
    case 'disconnected':
    case 'failed': return 'mdi-close'
    default: return 'mdi-help'
  }
}

const getConnectionText = (state: RTCPeerConnectionState) => {
  switch (state) {
    case 'connected': return 'Connected'
    case 'connecting': return 'Connecting...'
    case 'new': return 'Establishing...'
    case 'disconnected': return 'Disconnected'
    case 'failed': return 'Failed'
    default: return 'Unknown'
  }
}

const isConnecting = (state: RTCPeerConnectionState) => {
  return ['connecting', 'new'].includes(state)
}

// Initialize devices on mount
onMounted(() => {
  webrtcStore.getAvailableDevices()
})
</script>

<template>
  <v-card elevation="2" class="ma-2">
    <v-card-title class="d-flex align-center">
      <v-icon start>mdi-microphone-settings</v-icon>
      Media Controls
    </v-card-title>

    <v-card-text>
      <!-- Main Controls -->
      <v-row class="mb-3">
        <v-col cols="12">
          <div class="d-flex gap-2 flex-wrap">
            <!-- Start/Stop Video -->
            <v-btn
                v-if="!webrtcStore.isMediaActive"
                color="primary"
                variant="flat"
                :loading="webrtcStore.isConnecting"
                @click="startMedia"
            >
              <v-icon start>mdi-video</v-icon>
              Start Video
            </v-btn>

            <!-- Video Toggle -->
            <v-btn
                v-else
                :color="webrtcStore.hasVideo ? 'success' : 'error'"
                :variant="webrtcStore.hasVideo ? 'outlined' : 'flat'"
                @click="toggleVideo"
            >
              <v-icon start>{{ webrtcStore.hasVideo ? 'mdi-video' : 'mdi-video-off' }}</v-icon>
              {{ webrtcStore.hasVideo ? 'Turn Off Video' : 'Turn On Video' }}
            </v-btn>

            <!-- Audio Toggle -->
            <v-btn
                v-if="webrtcStore.isMediaActive"
                :color="webrtcStore.hasAudio ? 'success' : 'error'"
                :variant="webrtcStore.hasAudio ? 'outlined' : 'flat'"
                @click="toggleAudio"
            >
              <v-icon start>{{ webrtcStore.hasAudio ? 'mdi-microphone' : 'mdi-microphone-off' }}</v-icon>
              {{ webrtcStore.hasAudio ? 'Mute' : 'Unmute' }}
            </v-btn>

            <!-- Screen Share -->
            <v-btn
                v-if="webrtcStore.isMediaActive"
                :color="webrtcStore.isScreenSharing ? 'info' : 'default'"
                :variant="webrtcStore.isScreenSharing ? 'flat' : 'outlined'"
                :loading="webrtcStore.isConnecting"
                @click="toggleScreenShare"
            >
              <v-icon start>mdi-monitor-share</v-icon>
              {{ webrtcStore.isScreenSharing ? 'Stop Share' : 'Share Screen' }}
            </v-btn>

            <!-- Device Settings -->
            <v-btn
                variant="outlined"
                icon
                @click="showDeviceSettings = true"
            >
              <v-icon>mdi-cog</v-icon>
            </v-btn>

            <!-- Stop Media -->
            <v-btn
                v-if="webrtcStore.isMediaActive"
                color="error"
                variant="outlined"
                @click="stopMedia"
            >
              <v-icon start>mdi-stop</v-icon>
              Stop
            </v-btn>
          </div>
        </v-col>
      </v-row>

      <!-- Connection Status -->
      <v-row v-if="webrtcStore.isMediaActive && connectedCount > 0" class="mt-2">
        <v-col cols="12">
          <v-divider class="mb-3" />
          <div class="d-flex align-center justify-space-between mb-2">
            <div class="text-subtitle-2 text-medium-emphasis">
              <v-icon size="16" class="mr-1">mdi-connection</v-icon>
              Connected to {{ connectedCount }} participant{{ connectedCount !== 1 ? 's' : '' }}
            </div>

            <v-btn
                v-if="otherParticipantsCount > connectedCount"
                color="primary"
                variant="outlined"
                size="small"
                @click="webrtcStore.connectToAllParticipants"
            >
              <v-icon start size="16">mdi-refresh</v-icon>
              Reconnect All
            </v-btn>
          </div>

          <!-- Connection Progress -->
          <div class="d-flex align-center gap-2">
            <v-progress-linear
                :model-value="connectionProgress"
                :color="connectionProgress === 100 ? 'success' : 'warning'"
                height="6"
                rounded
                class="flex-grow-1"
            />
            <div class="text-caption text-medium-emphasis">
              {{ connectedCount }}/{{ otherParticipantsCount }}
            </div>
          </div>
        </v-col>
      </v-row>

      <!-- Individual Connections -->
      <v-row v-if="webrtcStore.isMediaActive && peerConnectionsArray.length > 0">
        <v-col cols="12">
          <div class="text-subtitle-2 text-medium-emphasis mb-2">
            <v-icon size="16" class="mr-1">mdi-account-group</v-icon>
            Participant Connections
          </div>

          <div class="d-flex flex-column gap-2">
            <v-card
                v-for="peer in peerConnectionsArray"
                :key="peer.participantId"
                variant="outlined"
                class="pa-2"
            >
              <div class="d-flex align-center justify-space-between">
                <div class="d-flex align-center gap-2">
                  <v-avatar size="24" :color="getConnectionColor(peer.connection.connectionState)">
                    <v-icon size="16" color="white">
                      {{ getConnectionIcon(peer.connection.connectionState) }}
                    </v-icon>
                  </v-avatar>
                  <div>
                    <div class="text-body-2 font-weight-medium">{{ peer.userName }}</div>
                    <div class="text-caption text-medium-emphasis">
                      {{ getConnectionText(peer.connection.connectionState) }}
                    </div>
                  </div>
                </div>

                <!-- Connection Quality -->
                <div v-if="peer.connection.connectionState === 'connected'" class="d-flex gap-1">
                  <div class="connection-bar bg-success"></div>
                  <div class="connection-bar bg-success"></div>
                  <div class="connection-bar bg-success"></div>
                </div>

                <!-- Loading indicator -->
                <v-progress-circular
                    v-else-if="isConnecting(peer.connection.connectionState)"
                    size="20"
                    width="2"
                    indeterminate
                    color="primary"
                />
              </div>
            </v-card>
          </div>
        </v-col>
      </v-row>

      <!-- Quick Actions -->
      <v-row v-if="webrtcStore.isMediaActive && otherParticipantsCount > 0" class="mt-2">
        <v-col cols="12">
          <v-divider class="mb-3" />
          <div class="d-flex gap-2">
            <v-btn
                variant="outlined"
                size="small"
                @click="webrtcStore.connectToAllParticipants"
            >
              <v-icon start size="16">mdi-refresh</v-icon>
              Reconnect All
            </v-btn>
          </div>
        </v-col>
      </v-row>
    </v-card-text>

    <!-- Device Settings Dialog -->
    <v-dialog v-model="showDeviceSettings" max-width="500">
      <v-card>
        <v-card-title class="d-flex align-center">
          <v-icon start>mdi-cog</v-icon>
          Device Settings
        </v-card-title>

        <v-card-text>
          <!-- Video Device -->
          <v-select
              v-model="webrtcStore.selectedVideoDevice"
              :items="videoDeviceItems"
              label="Camera"
              prepend-icon="mdi-video"
              variant="outlined"
              class="mb-4"
              @update:model-value="onVideoDeviceChange"
          />

          <!-- Audio Device -->
          <v-select
              v-model="webrtcStore.selectedAudioDevice"
              :items="audioDeviceItems"
              label="Microphone"
              prepend-icon="mdi-microphone"
              variant="outlined"
              class="mb-4"
              @update:model-value="onAudioDeviceChange"
          />

          <!-- Quality Settings -->
          <v-select
              v-model="selectedQuality"
              :items="qualityOptions"
              label="Video Quality"
              prepend-icon="mdi-quality-high"
              variant="outlined"
              class="mb-4"
          />

          <!-- Refresh Devices -->
          <v-btn
              variant="outlined"
              block
              @click="refreshDevices"
          >
            <v-icon start>mdi-refresh</v-icon>
            Refresh Devices
          </v-btn>
        </v-card-text>

        <v-card-actions>
          <v-spacer />
          <v-btn @click="showDeviceSettings = false">
            Close
          </v-btn>
        </v-card-actions>
      </v-card>
    </v-dialog>
  </v-card>
</template>

<style scoped>
.gap-2 {
  gap: 8px;
}

.connection-bar {
  width: 3px;
  height: 12px;
  border-radius: 2px;
}
</style>
