// ui-nuxt/components/ChatMessage.vue
<template>
  <div
      :class="[
      'chat-message',
      { 'own-message': isOwnMessage },
      { 'mentioned': isMentioned }
    ]"
  >
    <!-- Message Bubble -->
    <div class="message-bubble">
      <!-- Message Header -->
      <div v-if="!isOwnMessage" class="message-header">
        <v-avatar size="24" :color="senderColor">
          <span class="text-caption text-white font-weight-bold">
            {{ senderInitials }}
          </span>
        </v-avatar>
        <span class="sender-name">{{ message.senderName }}</span>
        <span class="timestamp">{{ formattedTime }}</span>
      </div>

      <!-- Message Content -->
      <div class="message-content">
        <!-- Editing Mode -->
        <div v-if="isEditing" class="edit-container">
          <v-textarea
              v-model="editContent"
              variant="outlined"
              density="compact"
              rows="2"
              auto-grow
              :max-length="1000"
              hide-details
              @keydown.enter.exact.prevent="handleEdit"
              @keydown.escape="cancelEdit"
          />
          <div class="edit-actions">
            <v-btn
                size="small"
                variant="text"
                @click="cancelEdit"
            >
              Cancel
            </v-btn>
            <v-btn
                size="small"
                color="primary"
                variant="flat"
                :disabled="!editContent.trim() || editContent === message.content"
                @click="handleEdit"
            >
              Save
            </v-btn>
          </div>
        </div>

        <!-- Display Mode -->
        <div v-else>
          <!-- Reply Context -->
          <div v-if="message.replyTo" class="reply-context">
            <v-icon size="14" class="mr-1">mdi-reply</v-icon>
            <span class="text-caption text-medium-emphasis">
              Replying to a message
            </span>
          </div>

          <!-- Message Text -->
          <div class="message-text">
            {{ message.content }}
          </div>

          <!-- Edit Indicator -->
          <div v-if="message.edited" class="edit-indicator">
            <v-icon size="12" class="mr-1">mdi-pencil</v-icon>
            <span class="text-caption text-medium-emphasis">edited</span>
          </div>

          <!-- Reactions -->
          <div v-if="hasReactions" class="reactions">
            <v-chip
                v-for="(count, emoji) in message.reactions"
                :key="emoji"
                size="x-small"
                :color="hasUserReacted(emoji) ? 'primary' : 'default'"
                :variant="hasUserReacted(emoji) ? 'flat' : 'outlined'"
                class="reaction-chip"
                @click="toggleReaction(emoji)"
            >
              {{ emoji }} {{ count }}
            </v-chip>
          </div>
        </div>

        <!-- Own Message Timestamp -->
        <div v-if="isOwnMessage" class="own-timestamp">
          {{ formattedTime }}
          <v-icon v-if="message.edited" size="12" class="ml-1">mdi-pencil</v-icon>
        </div>
      </div>

      <!-- Message Actions Menu -->
      <v-menu v-model="showMenu" :close-on-content-click="false">
        <template #activator="{ props }">
          <v-btn
              v-bind="props"
              icon
              size="x-small"
              variant="text"
              class="message-menu-btn"
              @click="showMenu = true"
          >
            <v-icon size="16">mdi-dots-vertical</v-icon>
          </v-btn>
        </template>

        <v-list density="compact">
          <!-- React -->
          <v-list-item @click="showReactions = !showReactions">
            <template #prepend>
              <v-icon>mdi-emoticon-outline</v-icon>
            </template>
            <v-list-item-title>React</v-list-item-title>
          </v-list-item>

          <!-- Reply -->
          <v-list-item @click="replyToMessage">
            <template #prepend>
              <v-icon>mdi-reply</v-icon>
            </template>
            <v-list-item-title>Reply</v-list-item-title>
          </v-list-item>

          <!-- Edit (own messages only) -->
          <v-list-item v-if="canEdit" @click="startEdit">
            <template #prepend>
              <v-icon>mdi-pencil</v-icon>
            </template>
            <v-list-item-title>Edit</v-list-item-title>
          </v-list-item>

          <!-- Delete -->
          <v-list-item
              v-if="canDelete"
              @click="handleDelete"
              class="text-error"
          >
            <template #prepend>
              <v-icon color="error">mdi-delete</v-icon>
            </template>
            <v-list-item-title>Delete</v-list-item-title>
          </v-list-item>
        </v-list>
      </v-menu>

      <!-- Reaction Picker -->
      <div v-if="showReactions" class="reaction-picker">
        <v-card elevation="4" class="pa-2">
          <div class="d-flex gap-1 flex-wrap">
            <v-btn
                v-for="emoji in quickReactions"
                :key="emoji"
                size="small"
                variant="text"
                @click="toggleReaction(emoji)"
            >
              {{ emoji }}
            </v-btn>
          </div>
        </v-card>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { useChatStore } from '../stores/chat'
import { useRoomStore } from '../stores/room'
import type { ChatMessage } from '../types/chat.types'

interface Props {
  message: ChatMessage
}

const props = defineProps<Props>()

// Stores
const chatStore = useChatStore()
const roomStore = useRoomStore()

// Local state
const isEditing = ref(false)
const editContent = ref(props.message.content)
const showMenu = ref(false)
const showReactions = ref(false)

// Quick reactions
const quickReactions = ['👍', '👎', '😀', '😂', '❤️', '🎉', '🔥', '💯']

// Computed
const isOwnMessage = computed(() =>
    props.message.senderId === roomStore.currentParticipant?.socketId
)

const canEdit = computed(() =>
    chatStore.canEditMessage(props.message)
)

const canDelete = computed(() =>
    chatStore.canDeleteMessage(props.message)
)

const isMentioned = computed(() =>
    chatStore.isMentioned(props.message)
)

const senderInitials = computed(() => {
  const words = props.message.senderName.split(' ')
  if (words.length >= 2) {
    return words[0][0] + words[1][0]
  }
  return words[0]?.slice(0, 2) || '??'
})

const senderColor = computed(() => {
  // Generate consistent color based on sender name
  const colors = ['primary', 'secondary', 'success', 'info', 'warning', 'purple', 'indigo', 'teal']
  const hash = props.message.senderId.split('').reduce((a, b) => {
    a = ((a << 5) - a) + b.charCodeAt(0)
    return a & a
  }, 0)
  return colors[Math.abs(hash) % colors.length]
})

const formattedTime = computed(() => {
  const date = new Date(props.message.timestamp)
  return date.toLocaleTimeString([], {
    hour: '2-digit',
    minute: '2-digit'
  })
})

const hasReactions = computed(() =>
    props.message.reactions && Object.keys(props.message.reactions).length > 0
)

// Methods
const startEdit = () => {
  isEditing.value = true
  editContent.value = props.message.content
  showMenu.value = false

  nextTick(() => {
    // Focus the textarea
    const textarea = document.querySelector('.edit-container textarea')
    if (textarea) {
      (textarea as HTMLTextAreaElement).focus()
    }
  })
}

const cancelEdit = () => {
  isEditing.value = false
  editContent.value = props.message.content
}

const handleEdit = async () => {
  if (!editContent.value.trim() || editContent.value === props.message.content) {
    cancelEdit()
    return
  }

  try {
    await chatStore.editMessage(props.message.id, editContent.value)
    isEditing.value = false
  } catch (error) {
    console.error('Failed to edit message:', error)
    // Show error feedback
  }
}

const handleDelete = async () => {
  if (!confirm('Are you sure you want to delete this message?')) {
    return
  }

  try {
    await chatStore.deleteMessage(props.message.id)
    showMenu.value = false
  } catch (error) {
    console.error('Failed to delete message:', error)
    // Show error feedback
  }
}

const toggleReaction = async (emoji: string) => {
  try {
    if (hasUserReacted(emoji)) {
      await chatStore.removeReaction(props.message.id, emoji)
    } else {
      await chatStore.addReaction(props.message.id, emoji)
    }
    showReactions.value = false
    showMenu.value = false
  } catch (error) {
    console.error('Failed to toggle reaction:', error)
  }
}

const hasUserReacted = (emoji: string): boolean => {
  const currentUserId = roomStore.currentParticipant?.socketId
  if (!currentUserId || !props.message.reactions) return false

  const reactionUsers = props.message.reactionUsers?.[emoji] || []
  return reactionUsers.includes(currentUserId)
}

const replyToMessage = () => {
  chatStore.setReplyTo(props.message)
  showMenu.value = false
}

// Close menus when clicking outside
const closeMenus = () => {
  showMenu.value = false
  showReactions.value = false
}

// Watch for message updates
watch(() => props.message.content, (newContent) => {
  if (!isEditing.value) {
    editContent.value = newContent
  }
})
</script>

<style scoped>
.chat-message {
  position: relative;
  margin-bottom: 8px;
}

.own-message {
  display: flex;
  justify-content: flex-end;
}

.own-message .message-bubble {
  background-color: rgb(var(--v-theme-primary));
  color: white;
  border-bottom-right-radius: 4px;
}

.mentioned {
  background-color: rgba(var(--v-theme-warning), 0.1);
  border-left: 3px solid rgb(var(--v-theme-warning));
  padding-left: 8px;
  margin-left: -8px;
}

.message-bubble {
  position: relative;
  max-width: 80%;
  background-color: rgb(var(--v-theme-surface));
  border: 1px solid rgb(var(--v-theme-outline));
  border-radius: 12px;
  border-bottom-left-radius: 4px;
  padding: 8px 12px;
  word-wrap: break-word;
}

.message-header {
  display: flex;
  align-items: center;
  gap: 8px;
  margin-bottom: 4px;
}

.sender-name {
  font-weight: 500;
  font-size: 0.875rem;
  color: rgb(var(--v-theme-on-surface));
}

.timestamp {
  font-size: 0.75rem;
  color: rgb(var(--v-theme-on-surface-variant));
  margin-left: auto;
}

.message-content {
  position: relative;
}

.message-text {
  font-size: 0.875rem;
  line-height: 1.4;
  white-space: pre-wrap;
}

.own-message .message-text {
  color: white;
}

.edit-container {
  margin: -4px;
}

.edit-actions {
  display: flex;
  justify-content: flex-end;
  gap: 8px;
  margin-top: 8px;
}

.reply-context {
  display: flex;
  align-items: center;
  margin-bottom: 4px;
  padding: 4px 8px;
  background-color: rgba(var(--v-theme-primary), 0.1);
  border-radius: 4px;
  font-size: 0.75rem;
}

.edit-indicator {
  display: flex;
  align-items: center;
  margin-top: 4px;
  font-size: 0.75rem;
}

.own-message .edit-indicator {
  color: rgba(255, 255, 255, 0.7);
}

.reactions {
  display: flex;
  flex-wrap: wrap;
  gap: 4px;
  margin-top: 8px;
}

.reaction-chip {
  cursor: pointer;
  transition: all 0.2s ease;
}

.reaction-chip:hover {
  transform: scale(1.05);
}

.own-timestamp {
  display: flex;
  align-items: center;
  justify-content: flex-end;
  margin-top: 4px;
  font-size: 0.75rem;
  color: rgba(255, 255, 255, 0.7);
}

.message-menu-btn {
  position: absolute;
  top: 4px;
  right: 4px;
  opacity: 0;
  transition: opacity 0.2s ease;
}

.message-bubble:hover .message-menu-btn {
  opacity: 1;
}

.reaction-picker {
  position: absolute;
  top: 100%;
  right: 0;
  z-index: 10;
  margin-top: 4px;
}

/* Mobile responsive */
@media (max-width: 768px) {
  .message-bubble {
    max-width: 90%;
  }

  .message-menu-btn {
    opacity: 1;
  }
}
</style>

// ui/src/components/ChatMessage.tsx
// ui/src/components/Chat/ChatMessage.tsx - Fixed reaction positioning and self-reaction

import React, { useState } from 'react';
import { observer } from 'mobx-react-lite';
import chatStore from '@/stores/chat.store';
import roomStore from '@/stores/room.store';
import type { ChatMessage } from '@/types/chat.types';

interface ChatMessageProps {
    message: ChatMessage;
}

const QUICK_REACTIONS = ['👍', '👎', '😀', '😂', '❤️', '🎉', '🔥', '💯'];

const ChatMessage: React.FC<ChatMessageProps> = observer(({ message }) => {
    const [isEditing, setIsEditing] = useState(false);
    const [editContent, setEditContent] = useState(message.content);
    const [showMenu, setShowMenu] = useState(false);
    const [showReactions, setShowReactions] = useState(false);

    const isOwnMessage = message.senderId === roomStore.currentParticipant?.socketId;
    const canEdit = chatStore.canEditMessage(message);
    const isMentioned = chatStore.isMentioned(message);

    const handleEdit = async () => {
        if (!editContent.trim() || editContent === message.content) {
            setIsEditing(false);
            return;
        }

        try {
            await chatStore.editMessage(message.id, editContent);
            setIsEditing(false);
            setShowMenu(false);
        } catch (error) {
            console.error('Failed to edit message:', error);
            alert('Failed to edit message');
        }
    };

    const handleDelete = async () => {
        if (!confirm('Are you sure you want to delete this message?')) return;

        try {
            await chatStore.deleteMessage(message.id);
            setShowMenu(false);
        } catch (error) {
            console.error('Failed to delete message:', error);
            alert('Failed to delete message');
        }
    };

    const handleReaction = async (emoji: string) => {
        try {
            const hasReacted = chatStore.hasUserReacted(message, emoji);
            if (hasReacted) {
                await chatStore.removeReaction(message.id, emoji);
            } else {
                await chatStore.addReaction(message.id, emoji);
            }
            setShowReactions(false);
        } catch (error) {
            console.error('Failed to toggle reaction:', error);
        }
    };

    const formatTime = (timestamp: string) => {
        const date = new Date(timestamp);
        return date.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
    };

    const renderMentions = (content: string) => {
        const mentionRegex = /@(\w+)/g;
        const parts = content.split(mentionRegex);

        return parts.map((part, index) => {
            if (index % 2 === 1) { // This is a username
                const participant = roomStore.participants.find(p =>
                    p.userName.toLowerCase() === part.toLowerCase()
                );
                if (participant) {
                    return (
                        <span
                            key={index}
                            className="bg-blue-100 text-blue-800 px-1 rounded font-medium"
                        >
              @{part}
            </span>
                    );
                }
            }
            return part;
        });
    };

    // System message rendering
    if (message.type === 'system') {
        return (
            <div className="flex justify-center my-2">
                <div className="flex items-center gap-2 text-xs text-gray-500 bg-gray-100 px-3 py-1 rounded-full">
                    <div className="w-3 h-3 text-gray-400">
                        <svg fill="currentColor" viewBox="0 0 20 20">
                            <path fillRule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clipRule="evenodd" />
                        </svg>
                    </div>
                    <span>{message.content}</span>
                </div>
            </div>
        );
    }

    return (
        <div className={`flex gap-3 group ${isOwnMessage ? 'flex-row-reverse' : ''} ${
            isMentioned ? 'bg-blue-50 border-l-4 border-blue-400 pl-3 py-2 rounded-r-lg' : ''
        }`}>
            {/* Avatar */}
            <div className="flex-shrink-0">
                <div className="w-8 h-8 bg-blue-500 rounded-full flex items-center justify-center text-white text-sm font-medium">
                    {message.senderName.charAt(0).toUpperCase()}
                </div>
            </div>

            {/* Message Content */}
            <div className={`flex-1 max-w-xs ${isOwnMessage ? 'text-right' : ''}`}>
                {/* Header */}
                <div className={`flex items-center gap-2 mb-1 ${isOwnMessage ? 'flex-row-reverse' : ''}`}>
          <span className="text-sm font-medium text-gray-900">
            {isOwnMessage ? 'You' : message.senderName}
          </span>
                    <span className="text-xs text-gray-500">
            {formatTime(message.timestamp)}
          </span>
                    {message.edited && (
                        <span className="text-xs text-gray-400 italic">
              (edited)
            </span>
                    )}
                </div>

                {/* Message Body Container - FIXED: Proper positioning context */}
                <div className="relative">
                    {isEditing ? (
                        <div className="space-y-2">
              <textarea
                  value={editContent}
                  onChange={(e) => setEditContent(e.target.value)}
                  className="w-full p-2 text-sm border border-gray-300 rounded-lg resize-none focus:outline-none focus:ring-2 focus:ring-blue-500"
                  rows={2}
                  autoFocus
                  onKeyDown={(e) => {
                      if (e.key === 'Enter' && !e.shiftKey) {
                          e.preventDefault();
                          handleEdit();
                      } else if (e.key === 'Escape') {
                          setIsEditing(false);
                          setEditContent(message.content);
                      }
                  }}
              />
                            <div className="flex gap-2 justify-end">
                                <button
                                    onClick={() => {
                                        setIsEditing(false);
                                        setEditContent(message.content);
                                    }}
                                    className="px-2 py-1 text-xs text-gray-600 hover:text-gray-800"
                                >
                                    Cancel
                                </button>
                                <button
                                    onClick={handleEdit}
                                    className="px-2 py-1 text-xs bg-blue-600 text-white rounded hover:bg-blue-700"
                                >
                                    Save
                                </button>
                            </div>
                        </div>
                    ) : (
                        <>
                            {/* Message Bubble */}
                            <div className={`inline-block p-3 rounded-lg max-w-full break-words ${
                                isOwnMessage
                                    ? 'bg-blue-600 text-white'
                                    : isMentioned
                                        ? 'bg-blue-100 text-gray-900 border border-blue-200'
                                        : 'bg-gray-100 text-gray-900'
                            }`}>
                                <div className="text-sm whitespace-pre-wrap">
                                    {renderMentions(message.content)}
                                </div>
                            </div>

                            {/* FIXED: Reactions positioned directly below message bubble */}
                            {message.reactions && message.reactions.length > 0 && (
                                <div className={`flex flex-wrap gap-1 mt-2 ${isOwnMessage ? 'justify-end' : 'justify-start'}`}>
                                    {message.reactions.map((reaction: any) => (
                                        <button
                                            key={reaction.emoji}
                                            onClick={() => handleReaction(reaction.emoji)}
                                            className={`inline-flex items-center gap-1 px-2 py-1 rounded-full text-xs transition-colors ${
                                                chatStore.hasUserReacted(message, reaction.emoji)
                                                    ? 'bg-blue-100 text-blue-700 border border-blue-300'
                                                    : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
                                            }`}
                                        >
                                            <span>{reaction.emoji}</span>
                                            <span>{reaction.count}</span>
                                        </button>
                                    ))}
                                </div>
                            )}
                        </>
                    )}

                    {/* Message Actions - FIXED: Better positioning and self-reaction prevention */}
                    {!isEditing && !isOwnMessage && ( /* FIXED: Don't show actions on own messages for reactions */
                        <div className="absolute -top-2 -right-2 opacity-0 group-hover:opacity-100 transition-opacity">
                            <div className="flex gap-1">
                                {/* Reaction Button */}
                                <div className="relative">
                                    <button
                                        onClick={() => setShowReactions(!showReactions)}
                                        className="w-6 h-6 bg-gray-200 hover:bg-gray-300 rounded-full flex items-center justify-center"
                                    >
                                        <span className="text-xs">😊</span>
                                    </button>

                                    {/* FIXED: Better positioned reaction dropdown */}
                                    {showReactions && (
                                        <div className="absolute top-full right-0 mt-1 bg-white border border-gray-200 rounded-lg shadow-lg p-2 z-20">
                                            <div className="grid grid-cols-4 gap-1">
                                                {QUICK_REACTIONS.map((emoji) => (
                                                    <button
                                                        key={emoji}
                                                        onClick={() => handleReaction(emoji)}
                                                        className="w-8 h-8 text-lg hover:bg-gray-100 rounded flex items-center justify-center transition-colors"
                                                    >
                                                        {emoji}
                                                    </button>
                                                ))}
                                            </div>
                                        </div>
                                    )}
                                </div>
                            </div>
                        </div>
                    )}

                    {/* FIXED: Separate menu for own messages (edit/delete only) */}
                    {!isEditing && canEdit && (
                        <div className="absolute -top-2 -right-2 opacity-0 group-hover:opacity-100 transition-opacity">
                            <div className="relative">
                                <button
                                    onClick={() => setShowMenu(!showMenu)}
                                    className="w-6 h-6 bg-gray-200 hover:bg-gray-300 rounded-full flex items-center justify-center"
                                >
                                    <svg className="w-3 h-3 text-gray-600" fill="currentColor" viewBox="0 0 20 20">
                                        <path d="M10 6a2 2 0 110-4 2 2 0 010 4zM10 12a2 2 0 110-4 2 2 0 010 4zM10 18a2 2 0 110-4 2 2 0 010 4z" />
                                    </svg>
                                </button>

                                {showMenu && (
                                    <div className="absolute top-full right-0 mt-1 bg-white border border-gray-200 rounded-lg shadow-lg z-20">
                                        <button
                                            onClick={() => {
                                                setIsEditing(true);
                                                setShowMenu(false);
                                            }}
                                            className="w-full px-3 py-2 text-left text-sm hover:bg-gray-100 first:rounded-t-lg"
                                        >
                                            Edit
                                        </button>
                                        <button
                                            onClick={handleDelete}
                                            className="w-full px-3 py-2 text-left text-sm text-red-600 hover:bg-red-50 last:rounded-b-lg"
                                        >
                                            Delete
                                        </button>
                                    </div>
                                )}
                            </div>
                        </div>
                    )}
                </div>

                {/* Reply indicator */}
                {message.replyTo && (
                    <div className={`mt-1 text-xs text-gray-500 ${isOwnMessage ? 'text-right' : ''}`}>
                        <span>↳ Replying to message</span>
                    </div>
                )}
            </div>
        </div>
    );
});

export default ChatMessage;
