// ui-nuxt/components/chat/ChatInput.vue
<script setup lang="ts">
import { useChatStore } from '~/stores/chat.store'
import { useRoomStore } from '~/stores/room.store'
import { ref, computed, watch, nextTick, onUnmounted, onMounted } from 'vue'

// Stores
const chatStore = useChatStore()
const roomStore = useRoomStore()

// Local state
const message = ref('')
const isTyping = ref(false)
const showMentions = ref(false)
const mentionQuery = ref('')
const mentionPosition = ref(0)
const showEmojiPicker = ref(false)
const textareaRef = ref<HTMLTextAreaElement | null>(null)
const typingTimeoutRef = ref<NodeJS.Timeout | null>(null)

// Quick emojis
const quickEmojis = ['👍', '👎', '😀', '😂', '❤️', '🎉', '👏', '🔥']

// Computed
const canSendMessage = computed(() =>
    message.value.trim() && chatStore.canSendMessages && !chatStore.isSendingMessage
)

const mentionCandidates = computed(() => {
  if (!showMentions.value || !mentionQuery.value) return []

  return roomStore.participants.filter(participant => {
    // Don't mention self
    if (participant.socketId === roomStore.currentParticipant?.socketId) return false
    // Filter by query
    return participant.userName.toLowerCase().includes(mentionQuery.value.toLowerCase())
  }).slice(0, 5) // Limit to 5 suggestions
})

const characterCount = computed(() => message.value.length)
const isOverLimit = computed(() => characterCount.value > 1000)

// Methods
const handleInput = (event: Event) => {
  const target = event.target as HTMLTextAreaElement
  const value = target.value
  const cursorPosition = target.selectionStart

  message.value = value

  // Check for @ mentions
  const beforeCursor = value.substring(0, cursorPosition)
  const mentionMatch = beforeCursor.match(/@(\w*)$/)

  if (mentionMatch) {
    showMentions.value = true
    mentionQuery.value = mentionMatch[1]
    mentionPosition.value = cursorPosition - mentionMatch[1].length - 1
  } else {
    showMentions.value = false
    mentionQuery.value = ''
  }

  // Handle typing indicators
  if (value.trim() && !isTyping.value) {
    isTyping.value = true
    chatStore.sendTypingIndicator(true)
  }

  // Clear existing timeout
  if (typingTimeoutRef.value) {
    clearTimeout(typingTimeoutRef.value)
  }

  // Set new timeout to stop typing indicator
  typingTimeoutRef.value = setTimeout(() => {
    if (isTyping.value) {
      isTyping.value = false
      chatStore.sendTypingIndicator(false)
    }
  }, 1000)

  // Auto-resize textarea
  nextTick(() => {
    if (textareaRef.value) {
      textareaRef.value.style.height = 'auto'
      textareaRef.value.style.height = `${Math.min(textareaRef.value.scrollHeight, 120)}px`
    }
  })
}

const selectMention = (participant: any) => {
  if (!textareaRef.value) return

  const beforeMention = message.value.substring(0, mentionPosition.value)
  const afterMention = message.value.substring(textareaRef.value.selectionStart)
  const newMessage = `${beforeMention}@${participant.userName} ${afterMention}`

  message.value = newMessage
  showMentions.value = false
  mentionQuery.value = ''

  // Focus back to textarea
  nextTick(() => {
    if (textareaRef.value) {
      const newCursorPosition = mentionPosition.value + participant.userName.length + 2
      textareaRef.value.focus()
      textareaRef.value.setSelectionRange(newCursorPosition, newCursorPosition)
    }
  })
}

const addEmoji = (emoji: string) => {
  const cursorPos = textareaRef.value?.selectionStart || message.value.length
  const newMessage = message.value.slice(0, cursorPos) + emoji + message.value.slice(cursorPos)
  message.value = newMessage
  showEmojiPicker.value = false

  nextTick(() => {
    textareaRef.value?.focus()
    const newPos = cursorPos + emoji.length
    textareaRef.value?.setSelectionRange(newPos, newPos)
  })
}

const handleSend = async () => {
  if (!canSendMessage.value) return

  const messageToSend = message.value.trim()
  message.value = ''

  // Stop typing indicator
  if (isTyping.value) {
    isTyping.value = false
    chatStore.sendTypingIndicator(false)
  }

  try {
    // Extract mentions from message
    const mentions: string[] = []
    const mentionRegex = /@(\w+)/g
    let match

    while ((match = mentionRegex.exec(messageToSend)) !== null) {
      const username = match[1]
      const participant = roomStore.participants.find(p =>
          p.userName.toLowerCase() === username.toLowerCase()
      )
      if (participant && !mentions.includes(participant.socketId)) {
        mentions.push(participant.socketId)
      }
    }

    await chatStore.sendMessage(messageToSend, 'text')
  } catch (error) {
    console.error('Failed to send message:', error)
    // Restore message on error
    message.value = messageToSend
  }
}

const handleKeyDown = (event: KeyboardEvent) => {
  if (showMentions.value) {
    if (event.key === 'Escape') {
      showMentions.value = false
      mentionQuery.value = ''
      return
    }
    // Could add arrow key navigation here
  }

  if (event.key === 'Enter' && !event.shiftKey) {
    event.preventDefault()
    handleSend()
  }
}

// Cleanup on unmount
onUnmounted(() => {
  if (typingTimeoutRef.value) {
    clearTimeout(typingTimeoutRef.value)
  }
  if (isTyping.value) {
    chatStore.sendTypingIndicator(false)
  }
})

// Initialize chat when mounted
onMounted(async () => {
  await chatStore.initializeChat()
})
</script>

<template>
  <div class="chat-input-container pa-3">
    <!-- Mention Dropdown -->
    <v-menu
        v-model="showMentions"
        :close-on-content-click="false"
        location="top"
        offset="8"
    >
      <template #activator="{ props: menuProps }">
        <div v-bind="menuProps" style="position: absolute; top: 0; left: 0; width: 1px; height: 1px;" />
      </template>

      <v-card v-if="mentionCandidates.length > 0" max-width="300">
        <v-card-text class="pa-2">
          <div class="text-caption text-medium-emphasis mb-2">Select a person to mention:</div>
          <v-list density="compact">
            <v-list-item
                v-for="participant in mentionCandidates"
                :key="participant.socketId"
                @click="selectMention(participant)"
                class="mention-item"
            >
              <template #prepend>
                <v-avatar size="24" color="primary">
                  <span class="text-caption text-white">
                    {{ participant.userName.charAt(0).toUpperCase() }}
                  </span>
                </v-avatar>
              </template>
              <v-list-item-title class="text-sm">{{ participant.userName }}</v-list-item-title>
            </v-list-item>
          </v-list>
        </v-card-text>
      </v-card>
    </v-menu>

    <!-- Main Input Area -->
    <div class="d-flex flex-column gap-2">
      <!-- Textarea -->
      <div class="position-relative">
        <v-textarea
            ref="textareaRef"
            v-model="message"
            variant="outlined"
            placeholder="Type a message... (use @ to mention someone)"
            rows="1"
            auto-grow
            :max-rows="4"
            :disabled="!chatStore.canSendMessages"
            :error="isOverLimit"
            hide-details
            @input="handleInput"
            @keydown="handleKeyDown"
        />

        <!-- Emoji Button -->
        <v-btn
            icon
            size="small"
            variant="text"
            class="position-absolute emoji-btn"
            @click="showEmojiPicker = !showEmojiPicker"
        >
          <v-icon size="20">mdi-emoticon-outline</v-icon>
        </v-btn>
      </div>

      <!-- Input Actions Row -->
      <div class="d-flex align-center justify-space-between">
        <!-- Character Count -->
        <div class="text-caption" :class="isOverLimit ? 'text-error' : 'text-medium-emphasis'">
          {{ characterCount }}/1000
        </div>

        <!-- Send Button -->
        <v-btn
            color="primary"
            variant="flat"
            size="small"
            :disabled="!canSendMessage || isOverLimit"
            :loading="chatStore.isSendingMessage"
            @click="handleSend"
        >
          <v-icon start size="16">mdi-send</v-icon>
          Send
        </v-btn>
      </div>

      <!-- Quick Emojis -->
      <v-expand-transition>
        <div v-show="showEmojiPicker" class="emoji-picker pa-2 border rounded">
          <div class="text-caption text-medium-emphasis mb-2">Quick Emojis:</div>
          <div class="d-flex gap-1 flex-wrap">
            <v-btn
                v-for="emoji in quickEmojis"
                :key="emoji"
                size="small"
                variant="text"
                @click="addEmoji(emoji)"
            >
              {{ emoji }}
            </v-btn>
          </div>
        </div>
      </v-expand-transition>

      <!-- Mention Help -->
      <div v-if="message.includes('@') && !showMentions && mentionQuery" class="text-caption text-medium-emphasis">
        💡 Tip: Type @username to mention someone in the room
      </div>

      <!-- Error Message -->
      <v-alert
          v-if="isOverLimit"
          type="error"
          variant="tonal"
          density="compact"
          class="text-caption"
      >
        Message is too long. Please keep it under 1000 characters.
      </v-alert>
    </div>
  </div>
</template>

<style scoped>
.chat-input-container {
  border-top: 1px solid rgba(var(--v-theme-outline), 0.2);
}

.emoji-btn {
  top: 8px;
  right: 8px;
}

.mention-item {
  cursor: pointer;
  border-radius: 6px;
  margin-bottom: 2px;
}

.mention-item:hover {
  background-color: rgba(var(--v-theme-primary), 0.1);
}

.emoji-picker {
  background-color: rgb(var(--v-theme-surface));
  border: 1px solid rgba(var(--v-theme-outline), 0.2) !important;
}

.position-relative {
  position: relative;
}

.position-absolute {
  position: absolute;
}
</style>

// ui/src/components/ChatInput.tsx
// ui/src/components/Chat/ChatInput.tsx - Enhanced with @mention support

import React, { useState, useRef, useEffect } from 'react';
import { observer } from 'mobx-react-lite';
import chatStore from '@/stores/chat.store';
import roomStore from '@/stores/room.store';

const ChatInput: React.FC = observer(() => {
    const [message, setMessage] = useState('');
    const [isTyping, setIsTyping] = useState(false);
    const [showMentions, setShowMentions] = useState(false);
    const [mentionQuery, setMentionQuery] = useState('');
    const [mentionPosition, setMentionPosition] = useState(0);
    const textareaRef = useRef<HTMLTextAreaElement>(null);
    const typingTimeoutRef = useRef<NodeJS.Timeout | null>(null);

    // Auto-resize textarea
    useEffect(() => {
        if (textareaRef.current) {
            textareaRef.current.style.height = 'auto';
            textareaRef.current.style.height = `${Math.min(textareaRef.current.scrollHeight, 120)}px`;
        }
    }, [message]);

    // Handle mention detection
    const handleInputChange = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
        const value = e.target.value;
        const cursorPosition = e.target.selectionStart;

        setMessage(value);

        // Check for @ mentions
        const beforeCursor = value.substring(0, cursorPosition);
        const mentionMatch = beforeCursor.match(/@(\w*)$/);

        if (mentionMatch && mentionMatch[1]) {
            setShowMentions(true);
            setMentionQuery(mentionMatch[1].toLowerCase());
            setMentionPosition(cursorPosition - mentionMatch[1].length - 1);
        } else {
            setShowMentions(false);
            setMentionQuery('');
        }

        // Handle typing indicators
        if (value.trim() && !isTyping) {
            setIsTyping(true);
            chatStore.sendTypingIndicator(true);
        }

        // Clear existing timeout
        if (typingTimeoutRef.current) {
            clearTimeout(typingTimeoutRef.current);
        }

        // Set new timeout to stop typing indicator
        typingTimeoutRef.current = setTimeout(() => {
            if (isTyping) {
                setIsTyping(false);
                chatStore.sendTypingIndicator(false);
            }
        }, 1000);
    };

    // Handle mention selection
    const selectMention = (username: string) => {
        if (!textareaRef.current) return;

        const beforeMention = message.substring(0, mentionPosition);
        const afterMention = message.substring(textareaRef.current.selectionStart);
        const newMessage = `${beforeMention}@${username} ${afterMention}`;

        setMessage(newMessage);
        setShowMentions(false);
        setMentionQuery('');

        // Focus back to textarea
        setTimeout(() => {
            if (textareaRef.current) {
                const newCursorPosition = mentionPosition + username.length + 2;
                textareaRef.current.focus();
                textareaRef.current.setSelectionRange(newCursorPosition, newCursorPosition);
            }
        }, 0);
    };

    const handleSend = async () => {
        if (!message.trim() || !chatStore.canSendMessage) return;

        const messageToSend = message.trim();
        setMessage('');

        // Stop typing indicator
        if (isTyping) {
            setIsTyping(false);
            chatStore.sendTypingIndicator(false);
        }

        try {
            await chatStore.sendMessage(messageToSend);
        } catch (error) {
            console.error('Failed to send message:', error);
            alert('Failed to send message');
            // Restore message on error
            setMessage(messageToSend);
        }
    };

    const handleKeyDown = (e: React.KeyboardEvent) => {
        if (showMentions) {
            // Handle mention navigation
            if (e.key === 'Escape') {
                setShowMentions(false);
                setMentionQuery('');
                return;
            }
            // You could add arrow key navigation here
        }

        if (e.key === 'Enter' && !e.shiftKey) {
            e.preventDefault();
            handleSend();
        }
    };

    const handleEmojiClick = (emoji: string) => {
        const newMessage = message + emoji;
        setMessage(newMessage);
        textareaRef.current?.focus();
    };

    // Filter participants for mentions
    const mentionCandidates = roomStore.participants.filter(participant => {
        if (participant.socketId === roomStore.currentParticipant?.socketId) return false; // Don't mention self
        return participant.userName.toLowerCase().includes(mentionQuery);
    });

    const quickEmojis = ['👍', '👎', '😀', '😂', '❤️', '🎉', '👏', '🔥'];

    // Cleanup on unmount
    useEffect(() => {
        return () => {
            if (typingTimeoutRef.current) {
                clearTimeout(typingTimeoutRef.current);
            }
            if (isTyping) {
                chatStore.sendTypingIndicator(false);
            }
        };
    }, [isTyping]);

    if (!chatStore.canSendMessage) {
        return (
            <div className="p-3 text-center text-gray-500 text-sm">
                Chat is not available
            </div>
        );
    }

    return (
        <div className="p-3 space-y-2 relative">
            {/* Mention Dropdown */}
            {showMentions && mentionCandidates.length > 0 && (
                <div className="absolute bottom-full left-3 right-3 mb-2 bg-white border border-gray-200 rounded-lg shadow-lg max-h-40 overflow-y-auto z-10">
                    <div className="p-2 text-xs text-gray-500 border-b">
                        Type to mention someone:
                    </div>
                    {mentionCandidates.slice(0, 5).map((participant) => (
                        <button
                            key={participant.socketId}
                            onClick={() => selectMention(participant.userName)}
                            className="w-full flex items-center gap-2 p-2 hover:bg-gray-100 text-left"
                        >
                            <div className="w-6 h-6 bg-blue-500 rounded-full flex items-center justify-center text-white text-xs font-medium">
                                {participant.userName.charAt(0).toUpperCase()}
                            </div>
                            <span className="text-sm">{participant.userName}</span>
                            {participant.isCreator && (
                                <span className="text-xs text-blue-600 bg-blue-100 px-1 rounded">host</span>
                            )}
                        </button>
                    ))}
                </div>
            )}

            {/* Quick Emojis */}
            <div className="flex gap-1 flex-wrap">
                {quickEmojis.map((emoji) => (
                    <button
                        key={emoji}
                        onClick={() => handleEmojiClick(emoji)}
                        className="p-1 hover:bg-gray-100 rounded text-lg leading-none"
                        type="button"
                    >
                        {emoji}
                    </button>
                ))}
            </div>

            {/* Input Area */}
            <div className="flex gap-2 items-end">
                <div className="flex-1 relative">
          <textarea
              ref={textareaRef}
              value={message}
              onChange={handleInputChange}
              onKeyDown={handleKeyDown}
              placeholder="Type a message... (@username to mention, Enter to send, Shift+Enter for new line)"
              className="w-full p-2 pr-10 border border-gray-300 rounded-lg resize-none focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              rows={1}
              style={{ minHeight: '40px', maxHeight: '120px' }}
          />

                    {/* Character Count */}
                    <div className="absolute bottom-1 right-2 text-xs text-gray-400">
                        {message.length}/1000
                    </div>
                </div>

                {/* Send Button */}
                <button
                    onClick={handleSend}
                    disabled={!message.trim() || message.length > 1000}
                    className={`p-2 rounded-lg transition-colors ${
                        message.trim() && message.length <= 1000
                            ? 'bg-blue-600 text-white hover:bg-blue-700'
                            : 'bg-gray-300 text-gray-500 cursor-not-allowed'
                    }`}
                    type="button"
                >
                    <svg className="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
                        <path d="M10.894 2.553a1 1 0 00-1.788 0l-7 14a1 1 0 001.169 1.409l5-1.429A1 1 0 009 15.571V11a1 1 0 112 0v4.571a1 1 0 00.725.962l5 1.428a1 1 0 001.17-1.408l-7-14z" />
                    </svg>
                </button>
            </div>

            {/* Mention hint */}
            {showMentions && mentionCandidates.length === 0 && mentionQuery && (
                <div className="text-xs text-gray-500">
                    No participants found matching "{mentionQuery}"
                </div>
            )}

            {/* Message Validation */}
            {message.length > 1000 && (
                <p className="text-xs text-red-600">
                    Message is too long ({message.length}/1000 characters)
                </p>
            )}

            {/* Mention help hint */}
            {message.includes('@') && !showMentions && (
                <div className="text-xs text-gray-500">
                    💡 Tip: Type @username to mention someone in the room
                </div>
            )}
        </div>
    );
});

export default ChatInput;
